name: multiple-event-workflow
on:
  push:
  issues:
    types:
      - opened
    workflow-dispatch:


jobs:
  multiple-event-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo love scl
      - name: step2
        run: |
          echo love me
          echo lover
      - name: echo inputs
        run: |
          echo ${{inputs.name}}
          echo ${{inputs.environment}}