name: cicd-1
on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - dev
    paths:
      - 'my-app/**'
jobs:
  test:
    if: github.event.action == 'opened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
  image-build:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
  deploy:
    runs-on: ubuntu-latest
    needs: [image-build]
    steps:
      - name: Checkout # 주석추가
        uses: actions/checkout@v4
